### ISSUE TITLE
Wrong s3 URL for downloading corpus

### ISSUE THREAD

**Issue by fajri91** [windweller/DisExtract#1]
Hi there,
You forget to include "data" in the URL

I think the link for downloading the corpus should be:

https://s3-us-west-2.amazonaws.com/dissent/data/discourse_EN_ALL_and_then_because_though_still_after_when_while_but_also_as_so_although_before_if_2017dec21_train.tsv

**Comment by windweller** [comment]
Done! Thank you :) let me know if you run into other issues with the code or data!
