### ISSUE TITLE
aws s3 cp invalid argument type 

### ISSUE THREAD

**Issue by serenayj** [windweller/DisExtract#2]
Hi, I had trouble in downloading the corpus using `aws s3 cp https://s3-us-west-2.amazonaws.com/dissent/data/discourse_EN_ALL_and_then_because_though_still_after_when_while_but_also_as_so_although_before_if_2017dec21_train.tsv .`

It said 
`usage: aws s3 cp <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
Error: Invalid argument type`

**Comment by windweller** [comment]
Ah, great! Thanks for bringing this to my attention.

Amazon has changed its way for data downloading. The new link is:

```
aws s3 cp s3://dissent/data/discourse_EN_ALL_and_then_because_though_still_after_when_while_but_also_as_so_although_before_if_2017dec21_test.tsv .
```

I'll update the README accordingly.
